-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 18:28:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`datos_generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_generales` (
  `id` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `edad` INT NOT NULL,
  `dob` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `idexamen` INT NOT NULL,
  `ocupacion` VARCHAR(45) NULL,
  `edo_civil` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `sangre` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`examen_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examen_general` (
  `id` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `ta` INT NOT NULL,
  `fc` INT NOT NULL,
  `fr` INT NOT NULL,
  `temperatura` INT NOT NULL,
  `peso` INT NOT NULL,
  `altura` INT NOT NULL,
  `imc` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `id_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mydb`.`datos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examen_oftal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examen_oftal` (
  `id` INT NOT NULL,
  `id_pacien` INT NOT NULL,
  `ojo_izq` INT NULL,
  `ojo_der` INT NULL,
  `graduacion_lente_izq` INT NULL,
  `graduacion_lente_der` INT NULL,
  `dist_vision` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX ` id_paciente_idx` (`id_pacien` ASC) VISIBLE,
  CONSTRAINT ` id_paciente`
    FOREIGN KEY (`id_pacien`)
    REFERENCES `mydb`.`datos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cutaneo_subcut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cutaneo_subcut` (
  `id` INT NOT NULL,
  `id_pacien_cut` INT NOT NULL,
  `aspecto` VARCHAR(45) NULL,
  `distr_pilosa` VARCHAR(45) NULL,
  `lesiones` VARCHAR(45) NULL,
  `faneras` VARCHAR(45) NULL,
  `teji_cel_subcut` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pacientes_idx` (`id_pacien_cut` ASC) VISIBLE,
  CONSTRAINT `id_pacien_cut`
    FOREIGN KEY (`id_pacien_cut`)
    REFERENCES `mydb`.`datos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cabeza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cabeza` (
  `id` INT NOT NULL,
  `id_pacien_cabeza` INT NOT NULL,
  `craneoycara` VARCHAR(45) NULL,
  `cuero_cabelludo` VARCHAR(45) NULL,
  `region_frontal` VARCHAR(45) NULL,
  `region_orbito_nasal` VARCHAR(45) NULL,
  `region_orofaringea` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pacientes_idx` (`id_pacien_cabeza` ASC) VISIBLE,
  CONSTRAINT `id_pacien_cabeza`
    FOREIGN KEY (`id_pacien_cabeza`)
    REFERENCES `mydb`.`datos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfermedades` (
  `id` INT NOT NULL,
  `id_pacientes` INT NOT NULL,
  `enfermedad` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pacientes_idx` (`id_pacientes` ASC) VISIBLE,
  CONSTRAINT `id_pacientes`
    FOREIGN KEY (`id_pacientes`)
    REFERENCES `mydb`.`datos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
